# The settings for the database (mariadb)
database:
  root_password_random: true

  # If you want to control the root password, set root_password_random to false
  # and set a root_password:
  #root_password: fqT!%gLsB55cJ!ZD

sites:
  default:
    ### The "default" section is optional
    ### The default site does not match all domains not listed elsewhere
    database_name: default_site
    database_password: 9&2H$gb?cJR7z8cx
  
  mysite.com:
    alias:
      - www.mysite.com
      - blog.mysite.com
    ### You can control the name of the database if you like If not set.
    ### the default value is the same as your domain name
    # database_name: 

    # database_user_name
  #The most basic site can be configured with just a domain name
  t3.alicesu.ml:
  t4.alicesu.ml:
  t5.alicesu.ml:

## The optional auto backup and restore plan
backups:
  s3:
    ## Schedule in Cron schedule expression, see: https://crontab.guru/
    ## The schedule is required. Without it, the backup is disabled.
    schedule: "0 2 * * *"

    ## The bucket to store the backup. Optionally, you can provide this value
    ## using an environment variable BACKUP_BUCKET
    bucket: your_s3_bucket_name

    ## If enabled, when container starts with any of the two folders
    ##  /var/www/html and var/lib/mysql being empty,
    ## it be restored from the backup on S3 if available.
    auto_restore: true

    ## AWS key and secret key if you want to hard code them here.
    ## if  not provided, environment variables are used: AWS_ACCESS_KEY_ID, 
    ## AWS_SECRET_ACCESS_KEY, and AWS_REGION
    aws_access_key_id: your_aws_key
    aws_secret_access_key: your_aws_secret_key
    aws_region: us-east-1
